swagger: '2.0'
info:
  title: Gift Aid Service
  version: 1.0.0
basePath: /api
schemes:
  - https
paths:
  /giftaid:
    get:
      summary: Get the amount of gift aid reclaimable for donation amount
      parameters:
        - in: query
          name: amount
          type: number
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GiftAidResponse'
        '400':
          description: BadRequest
          schema:
            type: array
            items: 
              $ref: '#/definitions/ValidationError'
        '500':
            description: InternalServerError
  /giftaid/donor:
    post:
      summary: Takes donor details and returns donor details with a declarationId and the calculated Gift Aid.
      consumes:
        - application/json
      parameters:
      - in: body
        name: GiftAidDonorRequest
        description: object containing the donor's basic details
        schema:
          $ref: '#/definitions/GiftAidDonorRequest'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GiftAidDonorResponse'
        '400':
          description: BadRequest
          schema:
            type: array
            items: 
              $ref: '#/definitions/ValidationError'
        '500':
            description: InternalServerError


definitions:
  GiftAidResponse:
    type: object
    required:
      - donationAmount
      - giftAidAmount
    properties:
      donationAmount:
        type: number
      giftAidAmount: 
        type: number
  ValidationError:
    type: object
    required:
        - errorCode
        - errorDescription
    properties:
      errorCode:
        type: number
      errorDescription:
        type: string
  GiftAidDonorRequest:
    type: object
    required:
      - donationAmount
      - name
      - postcode
    properties:
      donationAmount:
        type: number
      name:
        type: string
      postcode:
        type: string
  GiftAidDonorResponse:
    type: object
    required:
      - donationAmount
      - name
      - postcode
      - giftAidAmount
      - declarationId
    properties:
      donationAmount:
        type: number
      name:
        type: string
      postcode:
        type: string
      giftAidAmount:
        type: number
      declarationId:
        type: number